### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ghost** [Magic-Nipples/Xash3D-VS2019#2]
When I Try It, I Notice Some Bug/Problem In The Engine:
For Some Reason, Some Gun Missing A Lil Screenshake When Shot (The Gif Was Compressed)
![Untitled1](https://user-images.githubusercontent.com/57027133/68988051-1dec5200-0864-11ea-93d6-6572e1bc6798.gif)

**Comment by Magic-Nipples** [comment]
This isn't an issue. The code base isn't finished so some features will be missing.
