### ISSUE TITLE
Release build

### ISSUE THREAD

**Issue by ma-choo** [Magic-Nipples/Xash3D-VS2019#3]
Hey, Nipples,

Can I download a build of your fork? I can't compile it on my computer at the moment.

Thank you.

**Comment by Magic-Nipples** [comment]
I don't currently have plans to release any compiled binaries as I don't support this branch anymore. I moved to this [here](https://github.com/Magic-Nipples/Xash3D-VS2019-Clean/releases/tag/4934)
